### ISSUE TITLE
Cheatsheet ACT-2011

### ISSUE THREAD

**Issue by gabrielcrepeault** [NicholasLangevin/Guide_de_survie_en_actuariat#33]
Yo @alec42 !,

Peut-être que tu l'avais déjà vu, mais si tu ne veux pas partir de zéro pour le cours ACT-2011 pour la cheatsheet (à la session d'hiver), moi et Nich on en a fait une  (qui contient de la matière seulement jusqu'à l'intra par contre ...). **Elle a été placée dans 00_Archive/ACT-2011**, car le nom du fichier n'est pas `cheatsht-...`. 

Je viens de tomber là-dessus en fouillant le répertoire, donc j'ouvre le issue juste pour te le rappeler en temps et lieu!

Ça va t'être surtout utile pour ne pas partir *from scratch* pour les graphiques de Put/Call/etc 😄

**Comment by alec42** [comment]
Wow, elle est vraiment bien faite ! :D 
Je vais certainement la continuer :)
