### ISSUE TITLE
Symbole actuariel

### ISSUE THREAD

**Issue by davebulaval** [NicholasLangevin/Guide_de_survie_en_actuariat#36]
Un projet de Vincent et moi ;).

https://vigou3.gitlab.io/actuarialsymbol/

Ma première publication en plus https://tug.org/TUGboat/tb38-3/tb120beauchemin.pdf.

**Comment by alec42** [comment]
Effectivement je l'utilise sans cesse maintenant, incroyablement utile et essentiel pour faire n'importe quoi actuariel en LaTeX!! :) 
Merci ;)
